services:
  simulation:
    build: services/simulation/.
    container_name: husky_sim
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./try.sh:/try.sh
    restart: unless-stopped
    # devices:
    #  - "/dev/input/js0:/dev/input/ps4"
  
  glim:
    build: services/glim/.
    container_name: glim
    network_mode: host
    ipc: host
    pid: host
    tty: true
    stdin_open: true
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
    volumes:
      - ./services/glim/config:/glim/config
    command: ros2 run glim_ros glim_rosnode --ros-args -p config_path:=/glim/config
    restart: unless-stopped
