# base image ros 2 jazzy
FROM osrf/ros:jazzy-desktop

# Install mesa for windows rendering 
RUN apt-get update && apt-get install -y mesa-utils mesa-utils-extra libgl1-mesa-dri
ENV LIBGL_ALWAYS_SOFTWARE=1

# offboard computer setup from clearpath robotics tutorial (links in reame.md)
# ROS packages from clearpath's server
RUN apt-get -y install wget python3-vcstool python3-apt && \ 
    wget https://packages.clearpathrobotics.com/public.key -O - | apt-key add - && \
    sh -c 'echo \
        "deb https://packages.clearpathrobotics.com/stable/ubuntu $(lsb_release -cs) main" > \
        /etc/apt/sources.list.d/clearpath-latest.list' && \
    apt-get update
    
# update rosdep dependencies with the package built & hosted on Clearpath's servers
RUN wget \
    https://raw.githubusercontent.com/clearpathrobotics/public-rosdistro/master/rosdep/50-clearpath.list \
    -O /etc/ros/rosdep/sources.list.d/50-clearpath.list && \
    rosdep update

#This package will install launch and configuration files for visualising and interacting with the robot
RUN apt-get install -y ros-jazzy-clearpath-desktop

RUN apt-get install -y ros-jazzy-ros-gz 

# install clearpath sumulator (based on gazebo and has husky model in it)
RUN apt-get update && \ 
    apt-get install -y ros-jazzy-clearpath-simulator 


# put robot.yaml (with husky A200 specifications) into the right repo 
WORKDIR /root/clearpath/ 
COPY  src/robot.yaml /root/clearpath/ 

# copying launch to make this garbage simulator work correctly
COPY src/launch/robot_spawn.launch.py /opt/ros/jazzy/share/clearpath_gz/launch/ 

# Generate the setup.bash file
RUN ["/bin/bash", "-c", "source /opt/ros/jazzy/setup.bash \
    && ros2 run clearpath_generator_common generate_bash -s ~/clearpath"] 

# setup environment
RUN echo 'source /root/clearpath/setup.bash' >> /root/.bashrc

CMD ["/bin/bash", "-c", "ros2 launch clearpath_gz simulation.launch.py"]