# base docker from glim repo
FROM koide3/glim_ros2:jazzy

# Install mesa for windows rendering 
RUN apt-get update && apt-get install -y mesa-utils mesa-utils-extra libgl1-mesa-dri
ENV LIBGL_ALWAYS_SOFTWARE=1
